name: Walkdog - Robot CI

on:
  push:
    branches: [testes]
  pull_request:
    branches: [testes]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Usar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm ci
        working-directory: ./walkdog-robot # 👈 ajuste conforme o nome real da subpasta

      - name: Rodar testes
        run: npx robotframework tests/
        working-directory: ./walkdog-robot # 👈 se seus testes estiverem lá dentro
